### ISSUE TITLE
Server Code Patching error 

### ISSUE THREAD

**Issue by spolyak** [cycorp/api-suite#7]
I am trying to follow the cyc server patching instructions at:
http://dev.cyc.com/api/server-patching/

I followed the steps using the latest OpenCyc 4.0 server binaries (linux modified 2012-06-13) and the patch from:
Cyc Core Client Implementation 1.0.0-rc5.2
but it doesn't seem to work. I am getting...

```
;;; ... init/jrtl-init.lisp loaded; SHA-1: 4339ff6b6cf81ab2b39a4414d3df15d5b4769d96
;;; loading init/release-specific-init.lisp ...
;;; ... init/release-specific-init.lisp loaded; SHA-1: 29830c8808a3005178bb03c009b00caa8d45c180
;;; loading init/api-patches/init-api-patches.lisp ...
;;; loading init/api-patches/categorize-term-wrt-api.lisp ...

Error: DEFINE-EXTERNAL is not fboundp.
java.lang.Exception
        at com.cyc.tool.subl.jrtl.nativeCode.subLisp.Errors.possiblyCallErrorHandler(Errors.java:403)
        at com.cyc.tool.subl.jrtl.nativeCode.subLisp.Errors.error(Errors.java:198)
        at com.cyc.tool.subl.jrtl.nativeCode.subLisp.Errors.error(Errors.java:166)
        at com.cyc.tool.subl.jrtl.nativeCode.type.symbol.AbstractSubLSymbol.getFunction(AbstractSubLSymbol.java:114)
        at com.cyc.tool.subl.jrtl.nativeCode.type.core.AbstractSubLList.eval(AbstractSubLList.java:78)
        at com.cyc.tool.subl.jrtl.nativeCode.subLisp.Eval.eval(Eval.java:64)
        at com.cyc.tool.subl.jrtl.nativeCode.subLisp.Eval.load(Eval.java:129)
        at com.cyc.tool.subl.jrtl.nativeCode.subLisp.UnaryFunction_load50.processItem(Unknown Source)
        at com.cyc.tool.subl.jrtl.nativeCode.subLisp.Functions.funcall(Functions.java:78)
        at com.cyc.tool.subl.jrtl.nativeCode.type.operator.AbstractSubLFunction.evalViaApply(AbstractSubLFunction.java:151)
        at com.cyc.tool.subl.jrtl.nativeCode.type.core.AbstractSubLList.eval(AbstractSubLList.java:80)
        at com.cyc.tool.subl.jrtl.nativeCode.subLisp.SubLSpecialOperatorDeclarations.list_progn(SubLSpecialOperatorDeclarations.java:1083)
        at com.cyc.tool.subl.jrtl.nativeCode.subLisp.SubLSpecialOperatorDeclarations.punless(SubLSpecialOperatorDeclarations.java:178)
        at com.cyc.tool.subl.jrtl.nativeCode.subLisp.BinaryFunction$PunlessBinaryFunction.processItem(BinaryFunction.java:719)
        at com.cyc.tool.subl.jrtl.nativeCode.type.core.AbstractSubLList.eval(AbstractSubLList.java:86)
        at com.cyc.tool.subl.jrtl.nativeCode.subLisp.Eval.eval(Eval.java:64)
        at com.cyc.tool.subl.jrtl.nativeCode.subLisp.Eval.load(Eval.java:129)
        at com.cyc.tool.subl.jrtl.nativeCode.subLisp.UnaryFunction_load50.processItem(Unknown Source)
        at com.cyc.tool.subl.jrtl.nativeCode.subLisp.Functions.funcall(Functions.java:78)
        at com.cyc.tool.subl.jrtl.nativeCode.type.operator.AbstractSubLFunction.evalViaApply(AbstractSubLFunction.java:151)
        at com.cyc.tool.subl.jrtl.nativeCode.type.core.AbstractSubLList.eval(AbstractSubLList.java:80)
        at com.cyc.tool.subl.jrtl.nativeCode.subLisp.Eval.eval(Eval.java:64)
        at com.cyc.tool.subl.jrtl.nativeCode.subLisp.Eval.load(Eval.java:129)
        at com.cyc.tool.subl.jrtl.nativeCode.subLisp.UnaryFunction_load50.processItem(Unknown Source)
        at com.cyc.tool.subl.jrtl.nativeCode.subLisp.Functions.funcall(Functions.java:78)
        at com.cyc.tool.subl.jrtl.nativeCode.type.operator.AbstractSubLFunction.evalViaApply(AbstractSubLFunction.java:151)
        at com.cyc.tool.subl.jrtl.nativeCode.type.core.AbstractSubLList.eval(AbstractSubLList.java:80)
        at com.cyc.tool.subl.jrtl.nativeCode.subLisp.SubLSpecialOperatorDeclarations.list_progn(SubLSpecialOperatorDeclarations.java:1083)
        at com.cyc.tool.subl.jrtl.nativeCode.subLisp.SubLSpecialOperatorDeclarations.progn(SubLSpecialOperatorDeclarations.java:146)
        at com.cyc.tool.subl.jrtl.nativeCode.subLisp.BinaryFunction$PrognBinaryFunction.processItem(BinaryFunction.java:692)
        at com.cyc.tool.subl.jrtl.nativeCode.type.core.AbstractSubLList.eval(AbstractSubLList.java:86)
        at com.cyc.tool.subl.jrtl.nativeCode.subLisp.SubLMain.handleInitFormRunning(SubLMain.java:429)
        at com.cyc.tool.subl.jrtl.nativeCode.subLisp.SubLMain.handleInits(SubLMain.java:453)
        at com.cyc.tool.subl.jrtl.nativeCode.subLisp.SubLMain.access$200(SubLMain.java:43)
        at com.cyc.tool.subl.jrtl.nativeCode.subLisp.SubLMain$2.safeRun(SubLMain.java:509)
        at com.cyc.tool.subl.jrtl.nativeCode.type.core.SubLProcess.run(SubProcess.java:123)

        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
        at com.cyc.tool.subl.jrtl.nativeCode.subLisp.SubLThread.run(SubThread.java:109)
```
and several
```
Continuable error: Failed to read from stream in readloop.
java.io.IOException: Bad file descriptor
        at java.io.FileInputStream.readBytes(Native Method)
        at java.io.FileInputStream.read(FileInputStream.java:272)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:273)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:283)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:325)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.fill(BufferedReader.java:154)
        at java.io.BufferedReader.readLine(BufferedReader.java:317)
        at java.io.BufferedReader.readLine(BufferedReader.java:382)
        at com.cyc.tool.subl.jrtl.nativeCode.subLisp.SubLReader.readLine(SubLReader.java:353)
        at com.cyc.tool.subl.jrtl.nativeCode.subLisp.SubLReader.askMultiChoiceQuestion(SubLReader.java:171)
        at com.cyc.tool.subl.jrtl.nativeCode.subLisp.SubLReader.askRestartChoiceQuestion(SubLReader.java:122)
        at com.cyc.tool.subl.jrtl.nativeCode.subLisp.Errors.error(Errors.java:205)
        at com.cyc.tool.subl.jrtl.nativeCode.subLisp.Errors.error(Errors.java:166)
```
any advice on how to address this so that I can have an API client talk to the OpenCyc server?

**Comment by spolyak** [comment]
is it the case that i need a ResearchCyc instance to allow patching and API clients to talk to it?

**Comment by davidaschneider** [comment]
That's correct.  OpenCyc doesn't currently support these APIs.  ResearchCyc 4.0q, the current release version, does support server patching, and will work with these APIs.

**Comment by spolyak** [comment]
ah. alright. will go acquire a ResearchCyc license and setup first then. thanks for the confirmation.

**Comment by cyc-dev** [comment]
This issue was moved to cycorp/cyc-issues#7
